9. View a separate page for each category with a list of related reviews
Iketyke/Ikes-games-frontend pull request #5
Opened 2022-12-08 15:09 UTC by Iketyke

2022-12-08 15:18 UTC, pkaodev commented on src/Pages/Search/Search.jsx
> +      setIsLoading(false);
you need to set isLoading to true at the start of this useEffect, otherwise it will always be permanently false after it is flipped

2022-12-08 15:20 UTC, pkaodev commented on src/Pages/Home/Home.jsx
> +        setReviews(filtered);
We don't want to get our category-specific games like this.  We want to use the queries we set up on our API (?category=strategy for example).  Please change the api request you are using so that it can handle queries, and remove this.

2022-12-08 15:22 UTC, pkaodev commented
A good start but a couple of things to change:
-Make it so that we get our category specific games by using a query to the api rather than the .filter method
-set loading to true at start of the useeffect.

Please submit another PR when this is done

2022-12-08 16:39 UTC, callumu21 requested changes
Selecting a category should update the URL, allowing a user to share that URL to access the list of associated reviews directly. It looks like you currently don't have a route for individual categories (e.g. /categories/:category_slug) meaning this isn't possible.

You also need to action Patrik's original comment, as currently you aren't resetting the loading state when filter is updated in the useEffect.

Once you've implemented these, pop in another PR and we'll take another look 👍

2022-12-08 16:39 UTC, callumu21 commented on src/Pages/Search/Search.jsx
> +      console.log(data)
This console.log should be removed

2022-12-08 16:39 UTC, callumu21 commented on src/Pages/Search/Search.jsx
> +      console.log(data)
In fact, Patrik's original comment still needs actioning. This line should be setIsLoading(true) or it won't be reset when filter is changed.

2022-12-09 10:58 UTC, pkaodev commented
Looks and works great now!  Merge away

2022-12-09 11:01 UTC, merged